/**
 * scripts/index-render.mjs
 *
 * 프로젝트 인덱스 파일(INDEX.html 또는 INDEX.md) 생성 스크립트이다.
 *
 * 역할 요약:
 *  chronicle이 관리하는 여러 문서 자원(ADR, 체인지로그, 릴리즈)의 현황을 한 곳에 모아
 *  프로젝트 인덱스 파일을 생성한다. 출력 형식은 설정의 index.output 확장자(.html/.md)에
 *  따라 자동 결정된다.
 *
 * 공개 내보내기(exports):
 *  - buildIndexModel({ cwd, cfg }): 설정의 sources 목록에 따라 각 자원의 현황 데이터를 수집한다.
 *  - renderIndexMarkdown(model): 모델을 마크다운 형식으로 렌더링한다.
 *  - renderIndexHtml(model): 모델을 HTML 형식으로 렌더링한다.
 *
 * CLI 사용 예:
 *  ```
 *  node scripts/index-render.mjs                     # INDEX.html 생성
 *  node scripts/index-render.mjs --config ./my.json  # 설정 파일 명시
 *  ```
 *
 * 사용처:
 *  - chronicle 스킬의 `/index` 커맨드에서 호출한다.
 *  - buildAdrIndex를 내부적으로 재사용하므로 adr-index.mjs와 연동된다.
 *
 * 읽기 대상: ADR 디렉터리(buildAdrIndex 경유), cfg.changelog.path 존재 여부.
 * 쓰기 대상: cfg.index.output (기본: docs/INDEX.html).
 */
import { existsSync } from 'node:fs';
import { join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadConfig } from './lib/config.mjs';
import { writeFile } from './lib/fsutil.mjs';
import { buildAdrIndex } from './adr-index.mjs';

/**
 * 설정의 sources 목록에 따라 각 자원의 현황 데이터를 수집하여 인덱스 모델을 구축한다.
 *
 * @param {object} options - 옵션 객체.
 * @param {string} [options.cwd=process.cwd()] - 프로젝트 루트 디렉터리.
 * @param {object} options.cfg - loadConfig()가 반환한 설정 객체.
 *   cfg.index.sources: 처리할 자원 목록. 예: ['adr', 'changelog', 'releases'].
 * @returns {{ adr: object|null, changelog: object|null, releases: object|null }}
 *   각 자원의 현황 데이터를 담은 모델 객체. sources에 없는 자원은 null이다.
 *   - model.adr: { count: number, dir: string } — ADR 총 개수와 디렉터리 경로.
 *   - model.changelog: { exists: boolean, path: string } — 파일 존재 여부와 경로.
 *   - model.releases: { provider: string } — 릴리즈 제공자(예: 'github').
 *
 * 처리 로직:
 *  - 'adr': buildAdrIndex()를 호출하여 ADR 행 배열을 얻고 길이를 count로 저장한다.
 *           buildAdrIndex는 디렉터리 없음, 파일 없음 등을 우아하게 처리해 빈 배열을 반환한다.
 *  - 'changelog': existsSync()로 파일 존재 여부만 확인한다. 내용 파싱은 하지 않는다.
 *  - 'releases': 설정의 provider만 기록한다. 실제 릴리즈 목록은 가져오지 않는다.
 *
 * sources에 없는 자원은 모델에 null로 남으며 렌더링 함수가 건너뛴다.
 */
export function buildIndexModel({ cwd = process.cwd(), cfg }) {
  const sources = cfg.index.sources || [];
  const model = { adr: null, changelog: null, releases: null };
  if (sources.includes('adr')) {
    // ADR 디렉터리를 스캔하여 총 ADR 수와 디렉터리 경로를 모델에 저장한다.
    const rows = buildAdrIndex({ cwd, cfg });
    model.adr = { count: rows.length, dir: cfg.adr.dir };
  }
  if (sources.includes('changelog')) {
    // 체인지로그 파일의 존재 여부와 경로만 모델에 저장한다(내용 미파싱).
    model.changelog = { exists: existsSync(join(cwd, cfg.changelog.path)), path: cfg.changelog.path };
  }
  if (sources.includes('releases')) {
    // 릴리즈 제공자(provider) 정보만 모델에 저장한다.
    model.releases = { provider: cfg.release.provider };
  }
  return model;
}

/**
 * 인덱스 모델을 마크다운 형식으로 렌더링한다.
 *
 * @param {{ adr, changelog, releases }} model - buildIndexModel()이 반환한 모델 객체.
 * @returns {string} 마크다운 형식의 인덱스 문자열.
 *
 * 출력 포맷:
 *  ```
 *  # Project Index
 *
 *  > Generated by chronicle.
 *
 *  - [Architecture Decision Records](docs/adr) — 42 records
 *  - [Changelog](CHANGELOG.md)
 *  - Releases — github
 *  ```
 *
 * 렌더링 규칙:
 *  - model.adr가 null이 아니면 ADR 링크와 개수를 추가한다.
 *  - model.changelog가 null이 아니고 파일이 존재하면(exists === true) 체인지로그 링크를 추가한다.
 *    파일이 존재하지 않으면 항목을 생략한다(깨진 링크 방지).
 *  - model.releases가 null이 아니면 릴리즈 제공자 정보를 추가한다.
 *
 * 이 함수의 출력은 renderIndexHtml()이 재사용한다.
 * 마크다운 링크 패턴 `[텍스트](경로)`를 HTML <a> 태그로 변환하는 로직이 renderIndexHtml에 있다.
 */
export function renderIndexMarkdown(model) {
  let out = `# Project Index\n\n> Generated by chronicle.\n\n`;
  if (model.adr) {
    out += `- [Architecture Decision Records](${model.adr.dir}) — ${model.adr.count} records\n`;
  }
  if (model.changelog && model.changelog.exists) {
    // 파일이 실제로 존재할 때만 링크를 추가한다(존재하지 않으면 생략).
    out += `- [Changelog](${model.changelog.path})\n`;
  }
  if (model.releases) {
    out += `- Releases — ${model.releases.provider}\n`;
  }
  return out;
}

/**
 * 인덱스 모델을 HTML 형식으로 렌더링한다.
 *
 * @param {{ adr, changelog, releases }} model - buildIndexModel()이 반환한 모델 객체.
 * @returns {string} 완성된 HTML 문서 문자열. 항상 개행 1개로 끝난다.
 *
 * 렌더링 방식:
 *  1. renderIndexMarkdown(model)을 먼저 호출하여 마크다운 문자열을 얻는다.
 *  2. 마크다운의 `- `로 시작하는 줄만 필터링하여 목록 항목으로 변환한다.
 *  3. 각 항목에서 마크다운 링크 패턴 `[텍스트](URL)`을 HTML `<a href="URL">텍스트</a>`로 변환한다.
 *     정규식: `/\[([^\]]+)\]\(([^)]+)\)/g` — 그룹1=링크텍스트, 그룹2=URL.
 *     이것이 이 모듈에서 구현되는 마크다운→HTML 앵커 변환 로직이다.
 *  4. 변환된 항목들을 <li> 태그로 감싸고 <ul>로 묶어 HTML에 삽입한다.
 *
 * HTML 구조:
 *  - 최소 CSS: 최대 너비 820px, 가운데 정렬, 시스템 폰트. 외부 파일 의존성 없음.
 *  - 항상 자체 완결된 단일 HTML 파일로 생성된다(이식성 최우선).
 *
 * 주의: 마크다운 링크가 없는 항목(예: `- Releases — github`)은
 * replace 패턴이 일치하지 않아 텍스트 그대로 <li>로 감싸진다.
 */
export function renderIndexHtml(model) {
  const md = renderIndexMarkdown(model);
  // `- `로 시작하는 마크다운 목록 줄만 필터링한다.
  const items = md.split('\n').filter((l) => l.startsWith('- '))
    .map((l) => {
      // `- ` 접두사 제거 후 마크다운 링크를 HTML <a> 태그로 변환한다.
      const inner = l.slice(2).replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
      return `<li>${inner}</li>`;
    }).join('\n');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Project Index</title>
<style>body{font-family:-apple-system,system-ui,sans-serif;max-width:820px;margin:2rem auto;padding:0 1rem}</style>
</head><body><h1>Project Index</h1><ul>\n${items}\n</ul></body></html>\n`;
}

/**
 * CLI 진입점: --config 옵션을 파싱하고 인덱스 파일을 생성한다.
 *
 * @param {string[]} argv - process.argv.slice(2)로 전달되는 CLI 인수 배열.
 *
 * 동작 흐름:
 *  1. --config 인수를 파싱한다.
 *  2. loadConfig()로 설정을 로드한다.
 *  3. buildIndexModel()로 인덱스 모델을 구축한다.
 *  4. cfg.index.output의 확장자(.html vs 그 외)에 따라 렌더링 함수를 선택한다.
 *     - .html → renderIndexHtml(model) 호출.
 *     - 그 외(.md 등) → renderIndexMarkdown(model) 호출.
 *     extname()으로 확장자를 추출하므로 'docs/INDEX.html', 'INDEX.MD' 모두 올바르게 처리된다.
 *  5. writeFile()로 결과를 파일에 기록한다.
 *  6. stderr에 기록된 파일 경로를 출력한다.
 */
function main(argv) {
  let config;
  // --config 인수를 파싱한다.
  for (let i = 0; i < argv.length; i++) if (argv[i] === '--config') config = argv[++i];
  const cfg = loadConfig({ cwd: process.cwd(), path: config });
  const model = buildIndexModel({ cwd: process.cwd(), cfg });
  const out = cfg.index.output;
  // 출력 파일 확장자에 따라 HTML 또는 마크다운 렌더러를 선택한다.
  const content = extname(out) === '.html' ? renderIndexHtml(model) : renderIndexMarkdown(model);
  writeFile(join(process.cwd(), out), content);
  process.stderr.write(`wrote ${out}\n`);
}

/**
 * 이 파일이 직접 실행될 때만 main()을 호출한다.
 * 다른 모듈에서 import 시에는 main()이 실행되지 않으므로 사이드이펙트가 없다.
 */
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2));
}
