// scripts/index-render.mjs
import { existsSync } from 'node:fs';
import { join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadConfig } from './lib/config.mjs';
import { writeFile } from './lib/fsutil.mjs';
import { buildAdrIndex } from './adr-index.mjs';

export function buildIndexModel({ cwd = process.cwd(), cfg }) {
  const sources = cfg.index.sources || [];
  const model = { adr: null, changelog: null, releases: null };
  if (sources.includes('adr')) {
    const rows = buildAdrIndex({ cwd, cfg });
    model.adr = { count: rows.length, dir: cfg.adr.dir };
  }
  if (sources.includes('changelog')) {
    model.changelog = { exists: existsSync(join(cwd, cfg.changelog.path)), path: cfg.changelog.path };
  }
  if (sources.includes('releases')) {
    model.releases = { provider: cfg.release.provider };
  }
  return model;
}

export function renderIndexMarkdown(model) {
  let out = `# Project Index\n\n> Generated by chronicle.\n\n`;
  if (model.adr) {
    out += `- [Architecture Decision Records](${model.adr.dir}) — ${model.adr.count} records\n`;
  }
  if (model.changelog && model.changelog.exists) {
    out += `- [Changelog](${model.changelog.path})\n`;
  }
  if (model.releases) {
    out += `- Releases — ${model.releases.provider}\n`;
  }
  return out;
}

export function renderIndexHtml(model) {
  const md = renderIndexMarkdown(model);
  const items = md.split('\n').filter((l) => l.startsWith('- '))
    .map((l) => {
      const inner = l.slice(2).replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
      return `<li>${inner}</li>`;
    }).join('\n');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Project Index</title>
<style>body{font-family:-apple-system,system-ui,sans-serif;max-width:820px;margin:2rem auto;padding:0 1rem}</style>
</head><body><h1>Project Index</h1><ul>\n${items}\n</ul></body></html>\n`;
}

function main(argv) {
  let config;
  for (let i = 0; i < argv.length; i++) if (argv[i] === '--config') config = argv[++i];
  const cfg = loadConfig({ cwd: process.cwd(), path: config });
  const model = buildIndexModel({ cwd: process.cwd(), cfg });
  const out = cfg.index.output;
  const content = extname(out) === '.html' ? renderIndexHtml(model) : renderIndexMarkdown(model);
  writeFile(join(process.cwd(), out), content);
  process.stderr.write(`wrote ${out}\n`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2));
}
